find_path(LIBSOCKET_INCLUDE_DIR NAMES libsocket/unixdgram.hpp)
find_library(LIBSOCKET_LIBRARY NAMES libsocket++.so)

set(LIBSOCKET_INCLUDE_DIRS ${LIBSOCKET_INCLUDE_DIR})
set(LIBSOCKET_LIBRARIES ${LIBSOCKET_LIBRARY})
